-- 코드를 작성해주세요
SELECT F.ID, FISH_NAME_INFO.FISH_NAME, F.LENGTH
FROM FISH_INFO F
JOIN FISH_NAME_INFO ON F.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE F.LENGTH = (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE = F.FISH_TYPE AND LENGTH > 10
)
ORDER BY F.ID;
